### ISSUE TITLE
Suggestion: Truncate address only when detect insufficient screen width

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#134]
* On each of the "Create a new account" pages (i.e. create username, save secret phrase, confirm secret phrase, and enter password screens) it shows the user's address "0x..." in full, but after signing up the "Accounts" page shows a truncated version of the same address even though there's sufficient space to show it in full in portrait view. Possibly consider only truncating the address when detect a screen size that isn't wide enough

**Comment by Tbaut** [comment]
The screen size will always be sufficient IMO because of the narrow electron window.
The reason why we truncated the address on the account overview is because users tend to try to select the address to copy it, which is not possible (because each account is a card).
Still we needed users to be able to see the full address at some point.. that's why it's fully visible in the account view, because they also can copy it.

Does that make sense to you?
