### ISSUE TITLE
Use BIP39/BIP44 for new account

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#207]
For historical reasons, Parity products use a non standard logic and words dictionary for account recovery phrases. The Parity recovery phrases are not compatible with wallets such as Metamask, Jaxx or MyCrytpo.

We should:
- Still support legacy parity seed phrase for account recovery
- Support BIP39 recovery phrases
- Implement and use BIP39 for new account generation.
- Use the 1st derivated address for creation and recovery by default (no choice given to the user for now)

**Comment by axelchalon** [comment]
In "Import account", what about asking the user what type of phrase he wants to recover from, before asking them to input the recovery phrase?

*screen 1:*
what method would you like to use to recover your account?
- standard phrase
- parity phrase (legacy)

*screen 2:*
type your recovery phrase

in the account creation we would use a bip39 phrase. is parity_generateSecretPhrase going to be updated with bip39? or should we generate the phrase on Fether's side?

**Comment by Tbaut** [comment]
I believe we are updating the relevant rust crypto library, for this issue https://github.com/paritytech/parity-signer/issues/154
Having an automated word detection (since word disctionnaries are fairly different) and retrieve the first account derivation for Bip39 is good enough for now. We should generate a 12 words recovery phrase for new accounts.

**Comment by axelchalon** [comment]
It looks like Parity has 7776 entries in [its wordlist](https://docs.rs/parity-wordlist/1.2.1/parity_wordlist/constant.WORDS.html) versus the 2018 entries of [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt), and the words are fairly different indeed, so automatic detection should work! BIP39 includes a checksum; Parity phrases are just random words; so in case a recovery phrase exclusively uses words that appear in both wordlists, we can check if it's a valid BIP39 phrase, and if not we consider the phrase to be a Parity legacy phrase.

Need to follow up on what's being done on the Rust side re bip39 (blocking)

Account recovery should also accept phrases with more than 12 words as well I imagine: `For BIP39 related stuff: both Trezor and Ledger default to 24 words (256 bits entropy), while popular web/mobile wallets (MetaMask/MyCrypto/Jaxx/BRD) default to 12 words (128 bits entropy). Out of the latter, only MyCrypto allows you to recover wallets for 12, 15, 18, 21 or 24 words, all others are hardcoded for 12 words, which means that if you have an actual hardware wallet, you can only recover it on another hardware wallet or MyCrypto (persumably also MEW and other stuff we haven’t tested`

**Comment by axelchalon** [comment]
Implementation-wise

**Create account**
- Rather than calling `parity_generateSecretPhrase` and `parity_newAccountFromPhrase`, we use some JS library (check work on Parity Signer / Metamask / MyCrypto) to generate a 12-word BIP39 phrase and derive the private key from it; we create the new account on the node via private key using `parity_newAccountFromSecret`

**Recover account**
- If the phrase entered is a 12-word to 24-word valid BIP39 phrase, we derive the private key and create the account on the node via `parity_newAccountFromSecret`
- Otherwise, if it's a 12-word phrase consisting solely of words from the Parity wordlist, we proceed as currently (`parity_newAccountFromPhrase`)
- Else, reject. (In case of brain wallet the user can still add the account by calling RPCs directly on the node)

No changes to the UI/UX
