### ISSUE TITLE
Inconsistent decimal places uses for Ether account balance

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#244]
on the "Accounts" page, if I select my new account, it navigates to the account page where it shows I have 0.00 ETH, and if I click that card, it takes me to a "Send Ether" page, where it shows the same card at the top, but it shows I have 0.000000 ETH. is there an opportunity to make the amount of decimal places shown consistent (i.e. 2 dp vs 6 dp).
if the user has less than 1 Szabo (i.e. 0.000001) it may not show their balance even though have a balance.

**Comment by Tbaut** [comment]
I really don't think dust is worth bothering about, showing 2 or 6 digits doesn't feel wrong IMO, it's really about showing more info on 1 specific account once you clicked on it.

However, I think we should show 0.99 instead of 1.00 on the screen overview and not round it. What do you think @amaurymartiny and @axelchalon  ?
