### ISSUE TITLE
Actual Gas Limit is ~67% of Estimated Gas Limit when Sending THIBCoin

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/fether#297]
When I was on the **Send THIBCoin** page and debugging (similar to Issue #295), the Estimated Transaction Cost/Fee (Ether) `values.gas.mul(toWei(values.gasPrice, 'shannon')).div(1000000000000000000).toString()` was 0.00011940375 and the Estimated Gas Limit `+values.gas` was 39801.25 (i.e. Estimated gas 31841, with buffer 39801.25). It differs from just sending Ether since we have to allow for costs associated with interacting with the token contract.

But after I sent the transaction, on [transaction on Etherscan](https://kovan.etherscan.io/tx/0xf434c2523a3453be4283521143671d0bf3b4cc0f9afc2b65971ea58dd0ab25cf) showed an Actual Gas Limit of 39801 (as expected) and the Gas Price of 3 Gwei (as was entered in the UI), but the Actual Gas Limit was 27041 (only 67.94% of the Estimated Gas Limit), such that the Actual Transaction Cost/Fee was 0.000081123 Ether (also ~67% of the Estimated Transaction Cost/Fee)

**Comment by Tbaut** [comment]
This is expected, we want to be safe and add a buffer (currently 25%) because in some rare cases, contracts are more complex than what the engine think they are. The gas estimation is not an exact science, this is the reason why we prefer to add a buffer. Better be positively surprised than burn ETH for nothing.
