### ISSUE TITLE
Latest binary does not run on macos

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/fether#401]
After #352, new binaries have been released (see the Draft v0.3.0 in the releases page), but error on launch.

<img width="421" alt="screenshot 2019-02-04 at 16 51 40" src="https://user-images.githubusercontent.com/1293565/52219627-50146080-289d-11e9-982a-13ee80234079.png">

Another way to repro: `yarn package` in the root folder, and open `packages/fether-electron/dist/mac/Parity Fether.app`

**Comment by ltfschoen** [comment]
Yes, I should have checked that the binaries build first.
I get the same error when I run
```
yarn package; open "./packages/fether-electron/dist/mac/Parity Fether.app"
```

**Comment by ltfschoen** [comment]
I've been able to resolve the error and build on macos. I've been able to update all the dependencies in fether-electron to the latest versions (except for pino-multi-stream). But with the latest pino and pino-pretty, it's not logging the `pino.info(...`'s to stdout when i change the code to `const pretty = Pino({ prettyPrint: { colorize: true, outputStream: process.stdout } });`, and since I haven't been able to figure out how to retain the functionality of logging to stdout with the latest pino version, I'm just going to leave pino as it is, since we just need ansi-styles to resolve the bug.
