### ISSUE TITLE
Clicking on "See it on BlockScout" opens the webpage 10+ times

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/fether#410]
**Repro:**
- send a tx
- on the Sent page, wait for the message on "See it on BlockScount"
- click on it

**Expected:**
- open the webpage once

**Actual**
- it opens the webpage 10+ times

**Notes:**
- macos mojave

Edit: Also reproduced on the feedback button

**Comment by ltfschoen** [comment]
I'm using macOS Mojave 10.14 with Google Chrome as default browser.
I haven't been able to reproduce either of the issues.
I've tried running it after installing it from a .dmg file, and I've tried both `yarn; yarn start` and `yarn; yarn build`

**Comment by axelchalon** [comment]
Cannot reproduce either (clicking on the Feedback button)

**Comment by Tbaut** [comment]
I can't reproduce as well (feedback button) :(

**Comment by amaurymartiny** [comment]
Me neither... I must have dreamt or did something wrong

**Comment by Tbaut** [comment]
Just had it (click on Blockscout link) it opened 4 tabs..

**Comment by Tbaut** [comment]
I could reproduce it by toggling the Fether windows using the taskbar icon.
Toggle Fether 1 time (so that the Fether window disappear and reappears), click the feedback button, it opens 2 tabs :)
Toggle the window x more times, it opens x+1 tabs :see_no_evil:

**Comment by axelchalon** [comment]
> I could reproduce it by toggling the Fether windows using the taskbar icon.
> Toggle Fether 1 time (so that the Fether window disappear and reappears), click the feedback button, it opens 2 tabs :)
> Toggle the window x more times, it opens x+1 tabs see_no_evil

Can reproduce

**Comment by ltfschoen** [comment]
If the user clicks the taskbar/tray icon it runs `onTrayClick` and if the Fether window is visible runs `hideWindow`, and when the user clicks when the Fether window isn't visible (hidden) it also runs `onTrayClick` again instead runs `showWindow`, which restores the Fether window to its previously saved position, and also sets up the listeners. The issue was that it was setting up the listeners again (i.e. `setupWinListeners` and `setupWin32Listeners`) each time the tray icon was clicked and the the Fether window wasn't visible, so there were duplicate listeners including the `on('new-window')` listener in `setupWinListeners`
