### ISSUE TITLE
Should the taskbar app hide on blur on macos?

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/fether#411]
Current behavior: opening and hiding Fether is done by clicking on the menubar icon

Expected behavior (for me, but open to discussion):
- open Fether by clicking on the menubar icon
- close Fether by either clicking on the menubar icon, or clicking anywhere else on the screen

**Comment by ltfschoen** [comment]
As a user with multiple windows, if I have the Fether window open in my favourite position (i.e. right side of screen in the middle), and say I have a browser window open behind it, it was annoying when it was "Always On Top" because i'd have to make the effort of clicking the little taskbar icon to hide the Fether window (which was often too much effort) to make Fether get out of the way so it wouldn't obstruct me from reading the contents of that browser window, so instead I'd just drag to move the Fether window to a different position all the time.
I think opening and closing Fether by clicking on the menubar icon is good (existing functionality), but I think clicking anywhere else on the screen should just make the Fether window blur (move behind the other window that the user clicked) rather than actually closing it.

I've created a PR https://github.com/paritytech/fether/pull/415 with the functionality.

**Comment by Tbaut** [comment]
I think we're all aligned now :)
