### ISSUE TITLE
Taskbar icon barely visible on Linux and pixelized on alt-tab

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#421]
![image](https://user-images.githubusercontent.com/33178835/52546621-533dae00-2dc1-11e9-8cdf-f949d9832ccf.png)

^ as you can see, the all black icon on the left is barely visible on Linux with a dark bar. Any way to keep the white circle for linux (as the task bar could be light or drark) ?

![image](https://user-images.githubusercontent.com/33178835/52546632-63ee2400-2dc1-11e9-9c56-257ac920d84e.png)
^ The icon when changing application with alt+tab is pixelized.

**Comment by ltfschoen** [comment]
@Tbaut I actually only added that black icon because Linux uses a 16x16 icon for both (as you can see the Riot icon is also pixelated), and our Fether icon with the white circle background wasn't showing any of the Fether icon details. I'll just replace the 16x16 black icon with the 16x16 Fether icon the way it was before.

**Comment by ltfschoen** [comment]
I also used that icon for macOS as a "template image" so it would work with different themes dark/light (see https://stackoverflow.com/a/41998326/3208553) but it's not supported on Windows/Linux

**Comment by ltfschoen** [comment]
I'm looking into it again now
