### ISSUE TITLE
Doc upgrade or "why so man semi-colons?"

### ISSUE THREAD

**Issue by stone212** [paritytech/fether#493]
Did a mariaDB expert write the doc? :)  Maybe you want to replace this:

```
sudo apt update;
sudo apt install -y git nodejs npm curl;
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -;
apt-get install -y nodejs;
sudo ln -s /usr/bin/nodejs /usr/bin/node;
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -;
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list;
sudo apt-get update && sudo apt-get install yarn;
sudo ln -s /usr/bin/yarn /usr/local/bin/yarn;
yarn global add windows-build-tools;
```

With this:

```
$ sudo apt update
$ curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ sudo ln -s /usr/bin/nodejs /usr/bin/node (<-- might not be necessary)
$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
$ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
$ sudo apt-get update && sudo apt-get install yarn
$ sudo ln -s /usr/bin/yarn /usr/local/bin/yarn
```

**Comment by ltfschoen** [comment]
Hi @stone212. Thanks for creating an issue!

I added it that way because our time is precious. Adding a semi-colon at the end of each line is like adding a `&&` at the end of each line. It provides users with the convenience of being able to just copy/paste all those lines of code into terminal, press the enter key, and come back some time later after getting a coffee to find it's all installed. If there are any lines of code that you don't need then you just don't copy/paste them.

If you don't add a `;` or `&&` at the end of each line and you copy/paste all those lines of code into a terminal, it will only run the first command, so you'll have to waste time manually entering each command and waiting indefinitely for it to finish when you could be doing something better with your time.

Others may disagree, but I don't see any benefit to adding `$ ` at the start of each line. We're already using Markdown with bash/shell syntax highlighting, and you can't copy/paste multiple lines of code as conveniently.

I would have liked to have moved this code into a bash script, but not everyone likes that approach, which I discovered in this PR (a shell script for a different repo) that wasn't merged https://github.com/paritytech/scripts/pull/56

As for the `(<-- might not be necessary)` line of code, I just left that there because I it may be necessary, and if it is, it may save the user from the mundane task of having to try and figure out the missing step. If it's not necessary I don't think it does any harm.

Some users may be running Fether just after initially setting up their OS, hence the reason why I've provided the initial steps of installing dependencies like Git, cURL, etc.

We might be able to update the first four lines as follows:

```bash
sudo apt update;
sudo apt install -y git curl;
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -;
sudo apt-get install -y nodejs;
```

Although I personally prefer using Node Version Manager (NVM) and Yarn Version Manager (YVM), so we could replace the Node.js and Yarn setup steps with the following or similar:

```bash
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash;
source ~/.bashrc;
command -v nvm;
nvm list;
nvm install v11.13.0;
nvm use v11.13.0;

curl -fsSL https://raw.githubusercontent.com/tophat/yvm/master/scripts/install.js | node
source ~/.yvm/yvm.sh

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -;
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list;
sudo apt-get update;
sudo apt-get install -y yarn;
sudo ln -s /usr/bin/yarn /usr/local/bin/yarn;
yvm list;
yvm use 1.15.2;
```

**Comment by stone212** [comment]
@ltfschoen Well two things.

1. I was also making changes to your code.  Some of the lines were not necessary/correct and I updated that.  The rest is formatting with a joke about the semicolon.

2. But you ask my opinion so I can tell you.

>  It provides users with the convenience of being able to just copy/paste all those lines of code into terminal, press the enter key, and come back some time later after getting a coffee to find it's all installed

Is that your goal?  I went to that page for instructions, not an automatic solution.  If you want an automatic solution you could have a script - not to cut and paste from the screen but actually an install script in the code.  If that is not part of your philosphy I think actually you are breaking that philosophy anyway by helping users cut and paste a large piece of code.  However https://github.com/paritytech/scripts/pull/56 is about the script trying to do everything.  A compromise is a script that checks for dependencies and quits if they don't exist.  As a systems admin I don't want a script to do it for me.  I want to know what I'm entering/doing.  And I *definitely* don't want a script installing something like node without asking me.  I don't think it's the job of the fether docs to be an install wizard but a recipe.

> As for the (<-- might not be necessary) line of code, I just left that there because I it may be necessary, and if it is, it may save the user from the mundane task of having to try and figure out the missing step

But now some users have the murderous task to try and figure out why they get an error.  If they are so un-technical they cut and paste commands this error might confuse them.

>  I don't see any benefit to adding $ at the start of each line

It's a style preference.  It is necessary in situations where someone might be root and I think it is good anyway because it tells me I am at a BASH prompt, not a node or mariaDB or psql prompt.  But it is a style choice.

> hence the reason why I've provided the initial steps of installing dependencies like Git, cURL, etc.

I usually require devs that write docs for me list the pre-requisites but not give steps to install.  Because now you are responsible for maintaining those instructions if these packages change their best practices for installing.  Too much.  Better to say :

```
### Pre-requisites

* nodejs 10.x
* build-essential
* curl

A technical user needs this list and nothing more.  A non-technical user learns better this way.
```

> so we could replace the Node.js and Yarn setup steps with the following or similar:

God I hate seeing those semicolons.  Anyway that works but only if you use NVM or YVM.  I actually don't know YVM but I don't like the idea of moving away from BASH so much.  Every programmer thinks that everyone wants to use his favorite tools.  A sysadmin like me manages thousands of packages in every language and it is frustrating to have to use the language/syntax of each programmer's favorite package manager.  PM2, pip, pear whatever.  I like to `apt install` any time I can because it is universal, and also because once you have a different package manager sometimes the processes are not controlled by standard *nix system services and that is also annoying.

You asked my opinion, I gave it.  No problem if you have a different one.
