### ISSUE TITLE
Use IPC instead of Websockets

### ISSUE THREAD

**Issue by Tbaut** [paritytech/fether#546]
- to prevent possible local access to any info sent locally to the node
- to avoid having to use connection tockens.

**Comment by stone212** [comment]
@Tbaut  This could be a useful option for people running Fether on the same computer they run Parity on.  But it makes Fether unusable for people who use it to provide a GUI for remote nodes using SSH tunnel.

**Comment by Tbaut** [comment]
That's right. The gist of Fether is to be the interface running on top of a local light client though, not to be the interface for a full node running somewhere. There are other interfaces for that (MyCrypto being one).

**Comment by stone212** [comment]
@Tbaut I do not understand the difference between local and full node but I think you are saying it is meant to be a light wallet client only, not an interface to the Parity node like Parity-JS was.  Is that correct?  MyCrypto does not fill that function either so I think with the end of Parity-JS there is no GUI interface for Parity equivalent to Mist.

**Comment by Tbaut** [comment]
Feel free to use a software that suits you more. You are not using Fether for what it's intended to be used for, we will not trade security for this use case.

**Comment by stone212** [comment]
@Tbaut

> Feel free to use a software that suit you more.

That didn't need to be said.  Please keep it civil, Tbaut.  I put a lot of work into posting to help find bugs and help Parity become better by explaining other use cases, etc.  I personally don't use any UI.

> You are not using Fether for what it's intended to be used for

Where do you have a site that states what Fether is intended to be used for?  Because at the moment it works with the SSH tunnel that is described on the Parity wiki.  At least, it did many months ago when I helped test it for you.  I have not used it since then.

> we will not trade security for this use case

What use case?  The use case of an SSH tunnel that the Parity wiki recommends?  The use case of a Parity node on a VPS?  The use case of a person living in Venezuela?  The use case where "Fether will automatically connect to any Parity Ethereum node that is already running (using WebSockets port 8546)."  (That is from your FAQ).

Exactly what use case is Fether for?  I think one problem is that you are not being clear about this when you say "Parity Fether aims to be the lightest and simplest decentralized wallet."  De-centralized sounds to me like the opposite of requiring that Fether runs on the same computer that the node runs on.
