### ISSUE TITLE
Error message when opening fether

### ISSUE THREAD

**Issue by Baer17** [paritytech/fether#593]
When openig fether the attached message appears.
[fether.log](https://github.com/openethereum/fether/files/5288178/fether.log)
![Error message fether](https://user-images.githubusercontent.com/71968771/94363473-a366a280-00c2-11eb-91f2-87aee9c1d74c.PNG)

**Comment by Tbaut** [comment]
This application isn't maintained any more and should not be used any more to keep you funds safe. Please use another wallet to access your funds.

**Comment by Baer17** [comment]
Difficult to transfer the funds if I can't open the wallet. Do you have a recommendation how to proceed?

**Comment by Tbaut** [comment]
Thankfully, Fether was built to not capture its users. You can recover your account on other wallets. For this you must have the mnemonic phrase (also called secret phrase) that was given to you when you created the account.
This is most important part of any account. It must be kept in a secure place because anyone in its possession can access the funds of the account. This phrase can be used in most ethereum wallets out there. I would recommend using the desktop client of MyCrypto https://download.mycrypto.com/

**Comment by axelchalon** [comment]
FWIW seems to be the same error as in https://github.com/openethereum/fether/issues/586 and in https://github.com/openethereum/fether/issues/564
